enum FilmsActionTypes {
  SET_FILMS_COUNT = "SET_FILMS_COUNT",
  SET_FILMS_ITEMS = "SET_FILMS_ITEMS",
  SET_FILM = "SET_FILM",
  SET_FILMS_LOADER = "SET_FILMS_LOADER",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
}

export default FilmsActionTypes