enum StarshipsActionTypes {
  SET_STARSHIPS_COUNT = "SET_STARSHIPS_COUNT",
  SET_STARSHIPS_ITEMS = "SET_STARSHIPS_ITEMS",
  SET_STARSHIP = "SET_STARSHIP",
  SET_STARSHIPS_LOADER = "SET_STARSHIPS_LOADER",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
}

export default StarshipsActionTypes