export const ROUTER_ID_INDEX_PAGE_POSTFIX = 'INDEX'

export enum LAYOUT_ID {
  USER = 'USER_LAYOUT',
  PEOPLE = 'PEOPLE_LAYOUT',
  PLANETS = 'PLANETS_LAYOUT',
  FILMS = 'FILMS_LAYOUT',
  SPECIES = 'SPECIES_LAYOUT',
  VEHICLES = 'VEHICLES_LAYOUT',
  STARSHIPS = 'STARSHIPS_LAYOUT',
}

export enum ROUTE_ID {
  HOME = `HOME_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  PEOPLE_INDEX = `PEOPLE_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  PLANETS_INDEX = `PLANETS_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  FILMS_INDEX = `FILMS_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  SPECIES_INDEX = `SPECIES_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  VEHICLES_INDEX = `VEHICLES_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  STARSHIPS_INDEX = `STARSHIPS_${ROUTER_ID_INDEX_PAGE_POSTFIX}`,
  PEOPLE_DETAILS = 'PEOPLE_DETAILS',
  PLANET_DETAILS = 'PLANET_DETAILS',
  FILM_DETAILS = 'FILM_DETAILS',
  SPECIE_DETAILS = 'SPECIE_DETAILS',
  VEHICLE_DETAILS = 'VEHICLE_DETAILS',
  STARSHIP_DETAILS = 'STARSHIP_DETAILS',
}

export const LAYOUT = {
  [LAYOUT_ID.USER]: {
    ID: LAYOUT_ID.USER,
    PATH: '/',
  },
  [LAYOUT_ID.PEOPLE]: {
    ID: LAYOUT_ID.PEOPLE,
    PATH: '/people',
  },
  [LAYOUT_ID.PLANETS]: {
    ID: LAYOUT_ID.PLANETS,
    PATH: '/planets',
  },
  [LAYOUT_ID.FILMS]: {
    ID: LAYOUT_ID.FILMS,
    PATH: '/films',
  },
  [LAYOUT_ID.SPECIES]: {
    ID: LAYOUT_ID.SPECIES,
    PATH: '/species',
  },
  [LAYOUT_ID.VEHICLES]: {
    ID: LAYOUT_ID.VEHICLES,
    PATH: '/vehicles',
  },
  [LAYOUT_ID.STARSHIPS]: {
    ID: LAYOUT_ID.STARSHIPS,
    PATH: '/starships',
  },
};



export const ROUTES = {
  [ROUTE_ID.HOME]: {
    ID: ROUTE_ID.HOME,
    PATH: '/',
  },
  [ROUTE_ID.PEOPLE_INDEX]: {
    ID: ROUTE_ID.PEOPLE_INDEX,
    PATH: '/people',
  },
  [ROUTE_ID.PLANETS_INDEX]: {
    ID: ROUTE_ID.PLANETS_INDEX,
    PATH: '/planets',
  },
  [ROUTE_ID.FILMS_INDEX]: {
    ID: ROUTE_ID.FILMS_INDEX,
    PATH: '/films',
  },
  [ROUTE_ID.SPECIES_INDEX]: {
    ID: ROUTE_ID.SPECIES_INDEX,
    PATH: '/species',
  },
  [ROUTE_ID.VEHICLES_INDEX]: {
    ID: ROUTE_ID.VEHICLES_INDEX,
    PATH: '/vehicles',
  },
  [ROUTE_ID.STARSHIPS_INDEX]: {
    ID: ROUTE_ID.STARSHIPS_INDEX,
    PATH: '/starships',
  },
  [ROUTE_ID.PEOPLE_DETAILS]: {
    ID: ROUTE_ID.PEOPLE_DETAILS,
    PATH: '/people/:id',
  },
  [ROUTE_ID.PLANET_DETAILS]: {
    ID: ROUTE_ID.PLANET_DETAILS,
    PATH: '/planets/:id',
  },
  [ROUTE_ID.FILM_DETAILS]: {
    ID: ROUTE_ID.FILM_DETAILS,
    PATH: '/films/:id',
  },
  [ROUTE_ID.SPECIE_DETAILS]: {
    ID: ROUTE_ID.SPECIE_DETAILS,
    PATH: '/species/:id',
  },
  [ROUTE_ID.VEHICLE_DETAILS]: {
    ID: ROUTE_ID.VEHICLE_DETAILS,
    PATH: '/vehicles/:id',
  },
  [ROUTE_ID.STARSHIP_DETAILS]: {
    ID: ROUTE_ID.STARSHIP_DETAILS,
    PATH: '/starships/:id',
  },
};
