enum VehiclesActionTypes {
  SET_VEHICLES_COUNT = "SET_VEHICLES_COUNT",
  SET_VEHICLES_ITEMS = "SET_VEHICLES_ITEMS",
  SET_VEHICLE = "SET_VEHICLE",
  SET_VEHICLES_LOADER = "SET_VEHICLES_LOADER",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
}

export default VehiclesActionTypes