enum PlanetsActionTypes {
  SET_PLANETS_COUNT = "SET_PLANETS_COUNT",
  SET_PLANETS_ITEMS = "SET_PLANETS_ITEMS",
  SET_PLANET = "SET_PLANET",
  SET_PLANETS_LOADER = "SET_PLANETS_LOADER",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
}

export default PlanetsActionTypes