enum SpeciesActionTypes {
  SET_SPECIES_COUNT = "SET_SPECIES_COUNT",
  SET_SPECIES_ITEMS = "SET_SPECIES_ITEMS",
  SET_SPECIE = "SET_SPECIE",
  SET_SPECIES_LOADER = "SET_SPECIES_LOADER",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
}

export default SpeciesActionTypes