enum PeopleActionTypes {
  SET_PEOPLE_COUNT = 'SET_PEOPLE_COUNT',
  SET_PEOPLE_ITEMS = 'SET_PEOPLE_ITEMS',
  SET_PERSON = 'SET_PERSON',
  SET_PEOPLE_LOADER = 'SET_PEOPLE_LOADER',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  FETCH_PEOPLE = 'FETCH_PEOPLE',
  FETCH_PEOPLE_ID = 'FETCH_PEOPLE_ID',
}

export default PeopleActionTypes;
